<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15401" started-at="2020-11-18T12:23:09Z" finished-at="2020-11-18T12:23:24Z">
    <groups>
      <group name="smokeTest">
        <method signature="TC001_login.login()[pri:0, instance:testcases.TC001_login@5a8806ef]" name="login" class="testcases.TC001_login"/>
      </group> <!-- smokeTest -->
    </groups>
    <test name="Default test" duration-ms="15401" started-at="2020-11-18T12:23:09Z" finished-at="2020-11-18T12:23:24Z">
      <class name="testcases.TC001_login">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testcases.TC001_login@5a8806ef]" name="beforeSuite" is-config="true" duration-ms="145" started-at="2020-11-18T12:23:08Z" finished-at="2020-11-18T12:23:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="setData()[pri:0, instance:testcases.TC001_login@5a8806ef]" name="setData" is-config="true" duration-ms="0" started-at="2020-11-18T12:23:09Z" finished-at="2020-11-18T12:23:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.TC001_login@5a8806ef]" name="beforeMethod" is-config="true" duration-ms="7365" started-at="2020-11-18T12:23:09Z" finished-at="2020-11-18T12:23:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="login()[pri:0, instance:testcases.TC001_login@5a8806ef]" name="login" duration-ms="1634" started-at="2020-11-18T12:23:16Z" finished-at="2020-11-18T12:23:18Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[FAILED]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: FAILED
at utilities.Reporter.reportStep(Reporter.java:74)
at wrappers.GenericWrapper.webElementClick(GenericWrapper.java:189)
at pages.LoginPage.clickLogin(LoginPage.java:41)
at modules.ReusableModule.login(ReusableModule.java:24)
at testcases.TC001_login.login(TC001_login.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.TC001_login@5a8806ef]" name="afterMethod" is-config="true" duration-ms="14" started-at="2020-11-18T12:23:18Z" finished-at="2020-11-18T12:23:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.TC001_login@5a8806ef]" name="beforeMethod" is-config="true" duration-ms="5741" started-at="2020-11-18T12:23:18Z" finished-at="2020-11-18T12:23:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="login()[pri:0, instance:testcases.TC001_login@5a8806ef]" name="login" duration-ms="626" started-at="2020-11-18T12:23:23Z" finished-at="2020-11-18T12:23:24Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[FAILED]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: FAILED
at utilities.Reporter.reportStep(Reporter.java:74)
at wrappers.GenericWrapper.webElementClick(GenericWrapper.java:189)
at pages.LoginPage.clickLogin(LoginPage.java:41)
at modules.ReusableModule.login(ReusableModule.java:24)
at testcases.TC001_login.login(TC001_login.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.TC001_login@5a8806ef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2020-11-18T12:23:24Z" finished-at="2020-11-18T12:23:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testcases.TC001_login@5a8806ef]" name="afterSuite" is-config="true" duration-ms="451" started-at="2020-11-18T12:23:24Z" finished-at="2020-11-18T12:23:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testcases.TC001_login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
